### ISSUE TITLE
Is there a possibility to set a filename for downloading files?

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#1064]
Hi,
I am loading a file out of the SAP mime repository in my app and download it using the "iframe-method" from demo app 057. However it seems to be not possible to assign a filename with this approach and the file always has the name "download.xlsx". I am looking for something similar like the file uploader.

Input: Base64 string + filename -> Browser opens File Save Dialog

An alternative could be the <a> html tag like described here: https://stackoverflow.com/questions/14011021/how-to-download-a-base64-encoded-image

But I am not sure how to link this to an ui5 element like a button. Using plain HTML would be an option but it would be hard to make it look good with the surrounding ui5 elements.

Do you have an idea?

Best regards

**Comment by oblomov-dev** [comment]
Hi @LadwigDev,

so far the "iframe-method" is the only available option, but only because it was the quickest solution and not because it is the best or only way.

And yes this approach is very limited, and the ones you are recommend are better. I don't know how familiar you are with frontend development, but you can take a look to this:
https://community.sap.com/t5/technology-blogs-by-members/abap2ui5-11-extensions-ii-guideline-for-developing-new-features-in/ba-p/13576797
It's a step by step guide how to include your own JS as a custom control to abap2UI5 giving you the possibility to implement your own custom logic behind "good looking" UI5 elements.

Best would be developing a new Custom Control which includes the File Download functionality. 

Not sure if this helps you? 
Feel free to give it a try (or someone else here) and come back if you have questions. PRs are also welcome.

Best regards.

**Comment by choper725** [comment]
should be fairly easy to do if you have the b64 string at hand.
something along the lines on the spreadsheet cc just alot simpler on the press event..

you can create a small demo and i can try enhance it..

**Comment by LadwigDev** [comment]
Unfortunately I have currently no experience with JavaScript, I have created a small demo class with the default file name, the mime type and the base64 file content as class attributes.

I would really appreciate your help @choper725 

[Download File Demo Class.txt](https://github.com/abap2UI5/abap2UI5/files/14922571/Download.File.Demo.Class.txt)

**Comment by choper725** [comment]
great, let me see what i can do..

**Comment by oblomov-dev** [comment]
@choper725 cool, thank you!
https://twitter.com/abap2UI5/status/1778682397615096070

**Comment by LadwigDev** [comment]
Awesome, thanks a lot @choper725 !!!
