### ISSUE TITLE
Firefox: Debugging Tools - View (XML) isn't working

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1099]
I get this error when I try to go to View (XML) in debugger tools with Firefox. Chrome and Edge are working.
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/816dd911-264d-4c47-99c9-ea1c0b66ec58)
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/de78364d-642a-4bf6-b786-d300515bc11f)

This is the content of `sourceXml`

```XML
<mvc:View displayBlock="true" height="100%" xmlns="sap.m" xmlns:core="sap.ui.core" xmlns:form="sap.ui.layout.form" xmlns:mvc="sap.ui.core.mvc" xmlns:table="sap.ui.table">
	<Shell>
		<Page title="abap2UI5 - Hello World App">
			<form:SimpleForm editable="true">
				<form:content>
					<Title text="Make an input here and send it to the server..."/>
					<Label text="Enter your name"/>
					<Input value="{/XX/NAME}"/>
					<Button press="eB([&apos;BUTTON_POST&apos;])" text="post"/>
				</form:content>
			</form:SimpleForm>
		</Page>
	</Shell>
</mvc:View>
```

**Comment by oblomov-dev** [comment]
the xml prettifier runs into an error. till now to reduce developing efforts i only test with chrome and always recommend to everyone to use chrome only too. But i am sure you use firefox because a certain customer does not allow chrome (also had this problem often in the past in other contexts)?

maybe we should put firefox compatibility on the todo list.

**Comment by christianguenter2** [comment]
Thx for your feedback. Low priority.

**Comment by oblomov-dev** [comment]
I will close this for now. To keep efforts minimal, I will continue to focus solely on Chrome/Chromium. however if it becomes more important for you later, just reopen again that we can reassess then.
