### ISSUE TITLE
t_arg question

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#1114]
hi @oblomov-dev 
i was wondering, is it even poasible to somehow send back to be an object and interpret it as a toString in the t_arg table ??

**Comment by oblomov-dev** [comment]
you want to do something like:
oB( JSON.stringify( myFrontendObject ) ) ?
In the backend it can be recreated as an object with ajson.
Somehow there are limitations in the XML View Syntax but a lot is possible. Feel free to create a sample then i can check it.

**Comment by choper725** [comment]
yes, thats what i was thinking about..

the thing is in abap you can see the reutrn value is Object, just figured maybe we can strigify it before t_arg try to read it.

see demo 198 for simple button which in turn calls t_arg with event.mParameters should or expected to reutrn a json objcet of this.

let me know if i can help, i cant really find where this magic happens in http_post.. or am i way off..

**Comment by oblomov-dev** [comment]
thanks for the sample!

in general you did everything right, maybe the problem was that you stringify all arguments (better skip the first one and stringify each single value separate). updated now the main branch and the samples, check the latest PRs. you now get the parameter stringified in the backend and can make an json object out of it with the json parser of your choice.

**Comment by choper725** [comment]
thx ill check that, also found corcular reference issue that i solved, let me test your silution and maybe i can enhance it

**Comment by oblomov-dev** [comment]
yes feel free to find the best way of both approaches, just tested it quickly, there might some more situations we have to consider

**Comment by choper725** [comment]
ok ill add logix to avoid circular references.

can we use ajson at the event read to get the string to an abap table dynamiclly ?

**Comment by oblomov-dev** [comment]
you mean the framework should export the ajson object instead of a string? 

mhh so far we use a string_table here, so we need to change the type.
Or we add an additional parameter, t_arg_obj?

So yes of course this is possible, just need to check whats the best way. in general i want to keep the framework small and avoid to add too many logic into the framework. 

Maybe the end-user just gets a string and can use the json parser of his choice might also be an option?

**Comment by choper725** [comment]
yes i like this option! nothing need to be automated here imo.

ita just how can we parse a json string with ajson into an abap table ? i want to finish the example.

**Comment by oblomov-dev** [comment]
thats how you can read a attribute when it is a string:
```
 DATA(lv_id) = lo_json->get( `/id`).
```
but you can also do this when e.g. having a table:
```
            lo_json->to_abap(
*              EXPORTING
*                iv_corresponding = abap_false
              IMPORTING
               ev_container     = lt_table
            ).
```
or just extend the sample then i can check what you exactly need.

**Comment by choper725** [comment]
just PR,
circular reference seem to remove some of the object in the json.. will look into that once i have time,
didnt change your code, just tidied it up...

thx ! managed to figure out ajson also, so nice and clean :)

**Comment by oblomov-dev** [comment]
nice, thanks for updating the code.

**Comment by choper725** [comment]
no problem, will finish up both demos..

i think this small thing is a huge step forward regarding ui5 controls and event handling, great addition !
