### ISSUE TITLE
FLP Integration - data loss protection 

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1348]
Do we have means in abap2UI5 (flp integration) to implement data loss protection on back navigation? Something like this?
![grafik](https://github.com/user-attachments/assets/34f831df-17ca-415c-90dd-f484bb679a7c)

If not, any pointers I could follow?

Edit: Seems like this does the job. Though I'm not sure how to integrate this in abap2UI5...
https://help.sap.com/doc/saphelp_nw74/7.4.16/en-US/5d/c265ddbafb424b961bdf8f7c6bbe15/content.htm?no_cache=true

**Comment by oblomov-dev** [comment]
oh did not know this feature! if its just the single command:
```
sap.ushell.services.Container.setDirtyFlag(false);
```
then we can add it here as a frontend event:
https://github.com/abap2UI5/abap2UI5/blob/25fe14735454246035f153bac43eb450edd2ce0a/src/01/02/z2ui5_cl_core_http_get.clas.abap#L323
and name it maybe 'LP_SET_DATA_LOSS_ACTIVE' eg.

Feel free to give it a try, otherwise i can add it over the next week.

**Comment by christianguenter2** [comment]
Thx. I'll give it a try.

**Comment by oblomov-dev** [comment]
nice! if you need further help just create a PR with your changes
