### ISSUE TITLE
How can I test abap2UI5 locally?

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1562]
I ran `npm install` successfully and installed all available VSCode extensions for UI5/Fiori.

Though none of the npm scripts work for me.

`npm run start`
![image](https://github.com/user-attachments/assets/615eda13-c6ea-46dc-b54e-a28dc92f9e20)

`npm run start-local`
![image](https://github.com/user-attachments/assets/a02a1697-ca49-4912-8d92-3a7d58ee2451)

`npm run start-noflp`
![image](https://github.com/user-attachments/assets/99d14504-3310-4d28-a864-769cc3af6305)

What am I missing?

P.S. I'm on Windows 10 if that's important

**Comment by oblomov-dev** [comment]
i think you have to run without flp, try:
```
npm run start-noflp
```
you can also check here (will update and bring it to the documentation):
https://github.com/abap2UI5/abap2UI5/blob/main/app/README.md

**Comment by oblomov-dev** [comment]
and do one time a global renaming, that your abap backend system can be found:
replace in all files: `<<system>>` with your abap url.
for example here:
https://github.com/abap2UI5/abap2UI5/blob/main/app/ui5-mock.yaml#L20C18-L20C28

**Comment by christianguenter2** [comment]
Thx. I'm one step further with `npm run start-noflp`.
Now I'm getting CORS issues. What's the best way to deal with them?
![image](https://github.com/user-attachments/assets/8f495e1a-c428-4b3c-ac6c-28982be460c2)

**Comment by oblomov-dev** [comment]
Mhh normally this should not happen because all requests go to the local server and then via proxy to the abap system.

Did you renamed the server url correctly in all three files? I did the following:
<img width="555" alt="Code 2024-11-22 07 47 25" src="https://github.com/user-attachments/assets/7c6f70b8-db06-42b4-bea3-ab9d30b94f24">

I also tested it on my machine and updated the readme with all steps i did, check it here:
https://github.com/abap2UI5/abap2UI5/blob/main/app/README.md

It works on my side, here is my terminal:

<img width="1343" alt="Screenshot 2024-11-22 at 07 45 55" src="https://github.com/user-attachments/assets/0f51fe7f-6504-493d-9b16-fa2f3136a3ee">

<img width="600" alt="Safari 2024-11-22 07 53 52" src="https://github.com/user-attachments/assets/392fd6fe-3a79-46cc-914f-19a28bd67ee4">

<img width="600" alt="Safari 2024-11-22 07 53 58" src="https://github.com/user-attachments/assets/ec4a5971-358d-4f13-b303-079b7133b40c">

**Comment by christianguenter2** [comment]
Thx. I'll try again. Maybe it was too late yesterday ;-)

**Comment by christianguenter2** [comment]
@oblomov-dev 
link https://github.com/abap2UI5/abap2UI5/blob/main/app/README.md is dead. Did you move it?

**Comment by oblomov-dev** [comment]
yes its here now: https://abap2ui5.github.io/docs/advanced/extensibility/frontend.html

**Comment by christianguenter2** [comment]
Great. It's working for me now. Don't know what I did differently than last week. Thx a lot.
