### ISSUE TITLE
ABAP Docs / Constants

### ISSUE THREAD

**Issue by Xexer** [abap2UI5/abap2UI5#241]
Hey oblomov,

the demos are great, to see some working examples, but I am missing a documentation in form of ABAP Doc and some constants/enums (e.g. selection mode table -> Z2UI5_CL_APP_DEMO_19) to have the right values to fill in. It's a little bit hard to work with the methods, when I don't know what to give in.

Greetings

**Comment by oblomov-dev** [comment]
Hi Xexer,

you are right the class z2ui5_cl_xml_view can be more comfortable, there is no help and you have to guess which parameter you can import at the moment.

I would not use enums (although it would be the perfect use case for this) because it is then not downportable anymore. But the mentioned two possibilities are great and would make the development process a lot easier:
(1) Define constants for all possible parameters
(2) ABAPDoc that you can press during development F4 and see all available parameters

The only reason i did not add them so far is the extra expense in time that this needs. More or less you have to copy & paste the whole ui5.api to the class z2ui5_cl_xml_view and i started with the control names and properties first.

For the start i would recommend to check the UI5 API for that:
(1) Got to:
https://sapui5.hana.ondemand.com/#/api
(2) Search the control "m.table":
<img width="500" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/ab6c5e77-6368-4aed-8098-881bd009a1db">
(3) Activate "show borrowed properties":
<img width="500" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/06ff2645-ec50-4133-8094-5ac1a035aeb0">
(5) Search the control "mode":
<img width="500" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/08ae258d-355c-4359-b458-1a6d497e2bc4">
(6) And press sap.m.Listmode to see all available values:
<img width="1416" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/69cf068a-fc08-4e04-8f4b-54b250049525">

With the same way you can find all available parameters also for every other control.

If someone finds the time to add constants or ABAPDoc to z2ui5_cl_xml_view, i am happy to merge every pull request! Maybe it should also be possible to read the UI5 API with HTTP and then based on this create the class z2ui5_cl_xml_view with XCO including all controls, properties and possible values? Anyway it is on the to-do list for the future.

Best regards

**Comment by mbtools** [comment]
Replicating the complete UI5 doc into ABAP code isn't feasible. Maybe you just add the URL of each control as a ABAPDoc (unfortunately, ahref isn't supported but I think you can cut&paste the URL from the doc popup).

**Comment by oblomov-dev** [comment]
good idea with a link instead of copying! 
Are creating abapdoc comments any troubles when pulling it to low releases (7.02) or are they just ignored?

**Comment by mbtools** [comment]
they're treated as regular comments in lower releases. 

PS: The only issue I'm aware of is a `"!` before `class ... definition`, which AG is not able to deserialize.

**Comment by oblomov-dev** [comment]
No plans to add documentation to the actual view parser (effort too high). but we should replace this class from a certain point anyway and then it is a good time to include a proper documentation. so thank you for this idea and suggessting the use of abap doc. i close this one and we can follow up this idea here: https://github.com/abap2UI5/abap2UI5/issues/241
