### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#317]
Hi,

our first apps, using the ABAP2UI5 framework, are getting soon live.
Are you planning to provide a "stable" version for productive use?
The last update changed the framework massively and we had to adapt all our apps again.
Thanks a lot. It's really a great project!
Kind regards
Axel

**Comment by oblomov-dev** [comment]
Hi Axel,

nice to hear that you use abap2UI5! Yes the last change reorganized the whole client interface, i always try to avoid incompatibilities but the project is still new and is growing fast so i had to make these changes for future extensions. You can be sure that changes with this big incompatibilities will not happen so often anymore.

Maybe when you soon plan to use them productively you better choose the tags/releases instead of the main branch:
https://github.com/abap2UI5/abap2UI5/tags

But I will check again what is the best way to provide a stable version.

**Comment by oblomov-dev** [comment]
Added a FAQ and will collect information concerning this topic in the future here:
https://github.com/abap2UI5/abap2UI5/blob/main/docs/faq.md

There will be incompatible changes in the future too, but not as much as in the last month. Recommend to go only by using releases (not the main branch) and only update form time to time to reduce refactoring efforts.

**Comment by oblomov-dev** [comment]
for further questions, just create a new issue
