### ISSUE TITLE
UI Element ObjectNumber - Binding State 

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5#383]
Hi,

What is the correct notation for State = ?

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/ccce1341-dc30-4140-b25f-4e222603d879)

ABAP

`            )->object_number( number = '{MEASURE}' unit =  '{UNIT}' state = client->_bind_edit( '{MEASURE}'  '{UNIT}'  ) ).
`

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
Have you checked this example?
https://github.com/abap2UI5/demo-demos/blob/main/src/z2ui5_cl_app_demo_67.clas.abap

There parts is used in a similar way. You just need to call the method _bind in between and set the path parameter as true.
<img width="700" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/98e1a213-c7f9-4a2b-a925-8e088a1438aa">

**Comment by Th0masMa** [comment]
Hi @oblomov-dev,

Unfortunately it does not work. I've been trying all Sunday afternoon. Maybe you can take a look.
Below is my class.
I used the SAPUI5 example as a template.
[https://sapui5.hana.ondemand.com/#/entity/sap.m.ObjectNumber/sample/sap.m.sample.Table/code](url)

Best Regards
[Z2UI5_CL_APP_DEMO_71.txt](https://github.com/abap2UI5/abap2UI5/files/12064482/Z2UI5_CL_APP_DEMO_71.txt)

Thomas

**Comment by oblomov-dev** [comment]
HI @Th0masMa,

ok the hint with the _bind method was not the right way in this case, because we have a table here and aggregations. Did also not find a solution yet, but made a small step further. Somehow the formatter and type is not working but the parts function is working now.

I will try to take a deeper look to it in the next days, maybe there is a solution.

https://github.com/abap2UI5/demo-demos/blob/main/src/z2ui5_cl_app_demo_72.clas.abap
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/43d00479-3568-4d3d-a1de-2c3627704a43">

**Comment by oblomov-dev** [comment]
Extended again the example, the use of a formatter is not possible (or only with more extensions). But you can take now the example to see how to concatenate values with the path command.

Furthermore used the state property to change the color of the entries. Recommend to fill this value during runtime in the backend instead of using a formatter.

Check again: https://github.com/abap2UI5/demo-demos/blob/main/src/z2ui5_cl_app_demo_72.clas.abap
<img width="700" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/f6adde17-1930-4d3b-be75-014bd0db4f31">

**Comment by Th0masMa** [comment]
Guten Abend @oblomov-dev ,
Thank you very much. 
I like that too. Color aspects bring tabular data to better and better advantage.
I really liked the design with these wide gaps. Is something different than the columns, rows and cell display.
Or is there another possibility?

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/47d09626-f5fc-4353-b182-79f951986d9b)

Viele Grüße
Thomas

**Comment by oblomov-dev** [comment]
Moin @Th0masMa,

yes the output of tables is a lot improved with all these additional options!

Set the price column attribute "hAlign" to "End", i think this creates this behaviour:
```
<Column hAlign="End">
```
Best regards.

**Comment by Th0masMa** [comment]
Guten Abend @oblomov-dev ,

I had already done that.
See example Z2UI5_CL_APP_DEMO_72

`tab->columns(
        )->column( width = '12em'
            )->text( 'Product' )->get_parent(
        )->column( minScreenWidth = 'Tablet' demandPopin = abap_true
            )->text( 'Supplier' )->get_parent(
        )->column( minScreenWidth = 'Desktop' demandPopin = abap_true hAlign = 'End'
            )->text( 'Dimensions' )->get_parent(
        )->column( minScreenWidth = 'Desktop' demandPopin = abap_true hAlign = 'Center'
            )->text( 'Weight' )->get_parent(
         )->column( hAlign = 'End'
            )->text( 'Price' ).`

Gruß
Thomas

**Comment by oblomov-dev** [comment]
Ah ok so far that is also all i know, but there are always new things to discover in all these controls and properties :)
