### ISSUE TITLE
Nested Views - Two-Way binding doesn't work

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#408]
Hi,
I'm using the table selection mode approach like for demo "Z2UI5_CL_APP_DEMO_19", but in an nested master-detail view.
Unfortunately, the selection flag "SELKZ" will not be pushed back to the model data.
The method "NEST_VIEW_MODEL_UPDATE" of client class updates the view from the model, but not vice versa.
Thanks,
Kind regards
Axel

**Comment by oblomov-dev** [comment]
Hi Axel,

normally this should work but when you work with two views it can depend on where the table is placed an which view is updated etc. Need to take a look to it in detail. 

Is it possible for you to publish a small app which produces the problem?

I can copy and paste it and try to find the error.

Bets regards.

**Comment by axelmohnen** [comment]
Hi,
I created a demo class "z2ui5_cl_app_demo_66_2".
This is a mix between demo 19 and 66.

The issue occurs when the detailed page gets rendered after a line in the master tree gets selected.
I'm using multiple detail pages. Based on the tree line selected they get rendered separately.

[z2ui5_cl_app_demo_66_2.txt](https://github.com/abap2UI5/abap2UI5/files/12145297/z2ui5_cl_app_demo_66_2.txt)

Thanks,
Axel

**Comment by oblomov-dev** [comment]
Thank you for the coding example, very helpful, can copy&paste it and makes finding the error very easy.

Fixed it now with https://github.com/abap2UI5/abap2UI5/pull/410
The model was not always read correctly when using a nested view.

<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/0dbfc4ff-ce4c-4139-a236-16a5938484e2">

**Comment by oblomov-dev** [comment]
Can you check line 196, did you just miss to read the right table?

The data seems to be updated correctly.

Adjusted to:
<img width="610" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/dd2934fd-7e07-4c69-b3e5-4d8ec1202f1d">

**Comment by axelmohnen** [comment]
Sorry, this was the wrong example ;-)
Please find below the good one.
It contains a deep structure to the table data:
"ms_screen-data1-data2-table_data"

[Z2UI5_CL_APP_DEMO_66_3.txt](https://github.com/abap2UI5/abap2UI5/files/12146341/Z2UI5_CL_APP_DEMO_66_3.txt)

**Comment by oblomov-dev** [comment]
Thanks for the example, i checked it. The problem here is that your attribute name is longer than 30 characters and this creates an error when the table data is transformed to json and vice versa. Only 30 characters are allowed because of the use of /ui2/cl_json:
https://answers.sap.com/questions/12739849/field-name-gets-truncated-to-30-characters-while-d.html

I will check if a replacement of /ui2/cl_json makes sense, but this is a bigger topic. 

The quick fix would be to make the variables names shorter (less nested). I updated abap2UI5, you now will get an error:
<img width="657" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/d11f777b-f6c7-439e-a271-6e91613a14b0">

**Comment by oblomov-dev** [comment]
https://github.com/abap2UI5/abap2UI5/issues/412

**Comment by axelmohnen** [comment]
Hi,
thanks a lot for the analysis.
At least I understand now why it was working sometimes and sometimes not.
I will just re-organize my data model a bit.
Kind regards
Axel

**Comment by oblomov-dev** [comment]
@axelmohnen 
The problem is fixed now with https://github.com/abap2UI5/abap2UI5/issues/412
