### ISSUE TITLE
message manager messages.

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#476]
hi @oblomov-dev 
once we registered the message manager to the view, we can receive the messages in
sap.ui.getCore().getMessageManager().getMessageModel().oMessageManager.oMessageModel.oData

(you can check demo 67 for that)

how can we expose it to abap ?? (and also expose it once logging is active)

maybe even creating a global message model and use it once needed..

**Comment by oblomov-dev** [comment]
hi choper,

it should be no problem reading this and send it to the backend. but it costs additional runtime and i want to keep the frontend as small as possible, therefore the question first:
why do you want to use the frontend message object instead of creating a logging object in the backend and also make all checks in the backend?

do you also want to send messages from the backend to the frontend and fill the message object after a request?

best regards.

**Comment by choper725** [comment]
once we use a editable table, and now with the message manager we can tie an input with a validation,
now when there is an error on the input field we dont get the value in the backend.

i just think this is a generic way handling input validation on an app..

hence, without retreving the error messages, using message manager is pointless, that the user get an error but the backend is unaware of the errors

**Comment by choper725** [comment]
message manager dont handle be-> fe, for that we use messgae manager component in the view (like demo 38)

the purpose of getting the registered manager errors in the be, is for reacting to client errors in the view, without digging dipper to the data itself, for that we use the type of the input.

**Comment by oblomov-dev** [comment]
oh yes that would be nice, never took a closer look to the message manager. 

but when it is just one direction, i think we can keep everything small. will make a check before every request and if the message manager is bound i will send its messages to the backend and create a small table with:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/7d497975-a2b7-4aaf-b827-420281e0b162">
**fields:**
message
additionaltext
type

the ids are in an array, which fields are interesting?

**Comment by choper725** [comment]
sure that sounds great, that will do i think..
usually “where the error happend” is not relevant when registering the message manager to the view, but getting the id, is a nice future thinking

**Comment by oblomov-dev** [comment]
yeah i took the id/property now, it is more precise, but we can change everything again when other ways are better.

Updated main, should work now with:
<img width="900" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/92a9f4c3-403f-4853-b154-d3093b681863">

**Comment by choper725** [comment]
perfect ! ill try it out..

**Comment by choper725** [comment]
ATARGETS not getting back to abap,
its ok on the browser, but in the t_message_manager its empty.

**Comment by oblomov-dev** [comment]
fixed it!

**Comment by choper725** [comment]
hi @oblomov-dev 
i have to ask, after working with tables, and the lack of required functionality,
is it possible to consider adding a way to insert messages to the message manager ??

https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.core.message.MessageManager%23methods/addMessages

**Comment by oblomov-dev** [comment]
so a functionality like:
client->message_manager_add( `my message` ).

is this what you need?

adding this is no problem, we can just call the mentioned method after a roundtrip and then the message should be added to the message manager (without taking a deeper look to it, but we can just try it out).

**Comment by choper725** [comment]
yes thats all there is to it i think..
i dont know if clear all messages method is needed also,  maybe clearing the t_message_manager will be enough?

**Comment by oblomov-dev** [comment]
yes, could be, we will see. do you have an example app we can use to try this out? 
i can then add the method and check if it is working.

**Comment by choper725** [comment]
to the message manager demo 84

**Comment by oblomov-dev** [comment]
Updated the demo 84. You now have two new methods:
message_manager_add
message_maanger_clear

**Comment by choper725** [comment]
hi @oblomov-dev 
message_manager_add works after a roundtrip as expected,

 message_maanger_clear seems to not do anything..

btw,
maybe its only on my end but i am experiencing alot more loading times in the app, and even hangs when running the demo charts..
maybe its just my connection but still worth asking...

**Comment by oblomov-dev** [comment]
there was a bug with message_manager_clear, fixed this. 
after adding some message and clearing and doing an additional roundtrip the message manager is empty now. 
abap2UI5 calls the method removeAllMessages now, let me know if you need something else.

Performance:
Its always good that you let me know when you find out changes in the performance!
(1) I have all the time problems with the charts and other visualizations, the apps are hanging in the beginning because the ui5 libraries loads the controls (and i have no idea why this takes so long) but after the first initial load it works fine. but this seem to be more a ui5 problem... 🤷‍♂️
(2) another topic is the time per roundtrip means when you click a button or edit a field. made a lot of changes in the binding logic the last week, maybe the roundtrip takes longer now because of this. When you experience a longer waiting time, this is not good! i will check the logic again to improve performance. if you find out specific demo apps which are particulary slow, let me know that i can also use them for further investigation.

**Comment by choper725** [comment]
great thanks!!
the nested view III demo on my end take ling time adding rows, and loading on every added row for some reason

**Comment by oblomov-dev** [comment]
if you want you can test demo 082 and check chrome debugger tools for a speed check. on my side i get around 600ms per roundtrip:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/77c69de1-9dae-4bc0-bef0-fe7480c8257f">

And the same result i get for the nested views app and some others i checked. Means so far i do not find any app specific differences. In general 600 ms is ok but maybe could be faster, i will try to optimize this...

**Comment by choper725** [comment]
ill check it on my end, maybe its just my connection..
