### ISSUE TITLE
new rows in table as nested view

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#506]
hi @oblomov-dev 
im trying to create nested view with list and table.

and inserting rows from list to table..

something is happening when i append rows to the table from the list,
the first row is ok, but the second row appended is going on top the first one in the ui table..
something is wrong with the bind of the table or the nest model update ?

here is my demo for it..
[demo_97.txt](https://github.com/abap2UI5/abap2UI5/files/12418815/demo_97.txt)

**Comment by oblomov-dev** [comment]
checked it:
![image](https://github.com/abap2UI5/abap2UI5/assets/102328295/a9f43e49-341e-4846-9c29-f63f748dabb9)

I can press on every list element on the left side and then on the right side the row is displayed in the table. Is this the expected behaviour?

**Comment by oblomov-dev** [comment]
ah ok with every row click on the left side, the entry should be appendend to the right table?

**Comment by choper725** [comment]
yes, is it got to do with the binding ?? or i am doing something. wrong.

**Comment by oblomov-dev** [comment]
check out demo 97:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/08538143-f9d1-4400-b0cb-2ef6c34976fa">

Maybe the problem is solved, when you just update both models, because you also want to update the selected entry of the table on the left side:
https://github.com/abap2UI5/abap2UI5-samples/blob/7ba597551768b725fd48cdf42194e065958b1ace/src/z2ui5_cl_app_demo_97.clas.abap#L145

Best regards.

**Comment by choper725** [comment]
well its working..
the selected entry is getting pulled from the event..

does it suppose to behave this way ?? any way.. this solves it.. thx @oblomov-dev

**Comment by oblomov-dev** [comment]
Yes there are two json models one for the nested view and one for the normal one. Depending on the situation you have to decide which needs to be updated. It's a little bit tricky, we will find out if this is working in every situation or we need adjustments.

**Comment by oblomov-dev** [comment]
yes there are two view and two models and at the moment both views can update the backend values. so when you only update one view model it can happen that you overwrite later the actual values with a state from the past.

so i would recommend to update both all the time, but then there is the question why are you working with a nested view in this case?

i did not put too much effort in nested view so far, because i did not use them too much. just added the existing functionality. maybe there is the need to adjust the handling and add binding methods for two different models etc. but this also makes everything more complicated.

**Comment by choper725** [comment]
i see,
the use of nested view is to somewhat replicate sapui5 catalog demo app.
its a solution to update both models, im just writing down issues.. if a fix is needed or not its up to tou to decide, fixing everything at once surly not possible.

for the issue at hand, just pointing out that any type of using two models might cause an issue once update is needed, and updating both models not seem so intiative.
any way like you said before, updating both models solves the problem.
im just following up on this issue thats all

**Comment by oblomov-dev** [comment]
Yes it's fine! You are somehow the first who explores the nested views in abap2UI5. Just share your problems and snippets that's very helpful. 

Then we can see what we can make possible with this approach. To a certain level we can extend abap2UI5 and from a certain point on it will become too complicated but I have no idea where this is :) 

But I see that there is a problem when both views have editable values and they compete for changes... for example using an editable tree on the left side and a table on the right side will lead to encapsulate/decapsulate problems when both models are updated. At the moment fortunately you are using just tables.

**Comment by choper725** [comment]
oh i see, well until then :)

**Comment by oblomov-dev** [comment]
Updated the handling of model updates again, check demo 97.

You can now (optionally) bind the values to certain views (main, nested):
https://github.com/abap2UI5/abap2UI5-samples/blob/6e6687f9b5425e90a0943480960575b79c73473e/src/z2ui5_cl_app_demo_97.clas.abap#L100

Or here:
https://github.com/abap2UI5/abap2UI5-samples/blob/6e6687f9b5425e90a0943480960575b79c73473e/src/z2ui5_cl_app_demo_97.clas.abap#L50

Hopes that makes the handling more understandable and should also make it possible to handle editable trees and tables in different views synchronously.

**Comment by choper725** [comment]
that sound great ! thanks
ill check it out
