### ISSUE TITLE
demo 119 - driver js - not working

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#654]
Hi @oblomov-dev 
demo 119 stopped working after recent change PR..

**Comment by oblomov-dev** [comment]
forgot to update main repo, no it should work with https://github.com/abap2UI5/abap2UI5/pull/655

Same idea as with timer and title, try to keep only basic functionality in the index.html. added therefore the frontend_handler function also to the driver class. now everything can be maintained at one place. does this also work for you? let me know if you run into problems.

**Comment by choper725** [comment]
works for me..

can you please explain what is the purpose of the new namespace methods in all of this recent change ??

**Comment by oblomov-dev** [comment]
ok great! do a lot of changes at the moment to make the project ready for simplified maintenance. That’s why I clean up the index.html and want to make it to contain only the basic abap2UI5 funcitonality. (communication, model handling with data transfer, basic controller logic) I hope the rest can stay in custom controls and can be loaded on app level and only when it is needed.

furthermore i play around with different view classes which respect the namespaces of the ui5 controls more correctly. i am not completely happy with cl_xml_view because it can not handle controls with the same name which exist in different namespaces correctly. for example button in sap.m and sap.ui.webc.main. the more controls will be added in the future the more often we will run into problems with the cl_xml_view class. but everything just experimental for now, i also don't want to create incompatibilities so no plans to delete cl_xml_view, maybe the idea could be to replace it slowly when there is a better view class. but i will create a separate issue for this and explain this more and if you want you can also test it and share your ideas on that. i close this and will create a new one.

**Comment by oblomov-dev** [comment]
https://github.com/abap2UI5/abap2UI5/issues/660
