### ISSUE TITLE
script in popup

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#698]
[popup with script.txt](https://github.com/abap2UI5/abap2UI5/files/13516745/popup.with.script.txt)

getting error in console:
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/524b4b4a-116d-4103-b876-be7a68de9a4c)

the actual scenario im looking for is set attribute of control that is in a popup.

for this example i try setting the color of a label to blue, thorugh a function declared in the main view.
although, if running script in popup directly would be the same, as im trying to access a popup control.

**Comment by oblomov-dev** [comment]
i get an error beforehand:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/ea4affc6-2951-4810-bdd4-3a6d985d9a40">
Changed the source code to:
```abap
    DATA(script) = `` &&
                   `debugger; setBlackColor = function() {` && |\n| &&
                   `  var lbl = sap.ui.getCore().byId( 'lbl1' );` && |\n| &&
                   `  lbl.style.color = "blue";` && |\n| &&
                   `};`.
```
Now i can call the function in the console and it should also be possible in the popup:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/402b3b43-6f8d-4943-8128-aa1c59179b80">

**Comment by choper725** [comment]
the thing is how can i call it in popup ??
without an event..

**Comment by oblomov-dev** [comment]
Check out Sample 141:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_141.clas.abap

The function is now defined beforehand and it is called when rendering the popup:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/f1ee0a76-a7a3-4b71-963b-902db2b83b28">
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/e6d635db-44a6-4069-9c83-8d9554ea95ea">

But it seems that you want to change an UI5 control in this function. The problem is that at this moment the UI5 Control is not rendered, it is to early to call the function. Therefore i would recommend defining a custom control which changes the style of the Label and use your this cc:Label in the popup.

**Comment by choper725** [comment]
yes i understand, but the idea of creating a cc for every control in the sdk is pointless,
well ill try investigating why that happens, why this oFragmwnt error happen when using html tag..

**Comment by choper725** [comment]
> Nice! Did not know this way, always something new to learn :)

i didnt also, we both are learning :)

**Comment by choper725** [comment]
demo 141 changed back ?
