### ISSUE TITLE
Question to z2ui5_cl_demo_app_070 - sap.ui.table.Table

### ISSUE THREAD

**Issue by mansell** [abap2UI5/abap2UI5#712]
Hi Oblomov,
first I big thank you and congrats to this great framework. 
I try to git my first app but I'm struggling a bit with the details. The idea is to have a table with up to a 1000+ rows.
Your example demo_app_070 is great and includes a lot of nice features.
What I struggle is, that it shows only 10 rows in the "container".  I think I understand the function with dynamic data-loading in the background while scolling, but on a "big" screen I would like to show 20 rows. Or even adjust it dynamic to the page size.
I tried to include it in a page->scroll_container but somehow that doesn't work.
The same issue I have with the z2ui5_cl_demo_app_007  TreeTable example.
Do you have a solution or hint for me?
Thank you and kind regards
 Mansell

![2023-12-07 19_34_49-Start](https://github.com/abap2UI5/abap2UI5/assets/7797497/d143af92-3f96-4db5-9926-a4045918455a)

**Comment by oblomov-dev** [comment]
Hi mansell,

thank you and nice to hear that you like abap2UI5.

Have you checked the properties of ui.Table? There are a lot which influence the output and the number of rows. Never had this requirement before but maybe you find a property for this:
https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.table.Table%23controlProperties
<img width="1368" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/664490b4-9205-4152-9872-2f75a3adee70">

Besides that, i prefer using sap.m.Table instead of sap.ui.Table, it shows automatically as much rows as possible on the page, is this also an option for you?

Best regards.

**Comment by oblomov-dev** [comment]
btw, if an sap.m.table is also fine for you, you can check:
Z2UI5_CL_DEMO_APP_052

<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/546b245f-9916-40bc-b83a-556a69b9d3a2">

**Comment by mansell** [comment]
Hey Oblomov,
thank you for your fast response. Yes I thought I tried all the parameters. But I guess I lost the overview... with your hint to rowcount it work likes charm - I can give a fix number on visiblerowcount = '20' or put visiblerowcountmode = 'Auto' which fills up the space automatic. Which is exactly what I meant. So I can use sap.ui.table with all the nice features like sorting and filtering.
Thank you very much and I wish you much success with abap2ui5.

kind regards, Mansell
