### ISSUE TITLE
popup to open another popup

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#789]
hi @oblomov-dev ,
sorry for all the issues recently :)

just PR'd demo 161, which is an example of popup to open another popup,

the issue is, is that possible once the second popup is opened, upon closing it to go back to the 1st popup ??

im pretty sure that this was the case before all the massive js (http_get) changes...

EDIT:
i guess its possible to rerender to first popup again... not sure if it was like that...

**Comment by oblomov-dev** [comment]
Its good to have these issues! A lot of others will have the same question, so its good to answer it. And thank you for the demos, this is a big help, because its always the best explanation when you just can check the source code of a demo. I added it here:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/00243ab5-6b20-4af4-9bc9-d40510ba6b95">
Then everyone can see in the future how to solve this use case.

Yes i think you answered the question already by yourself. There never was a popup stack handling at the frontend, but you can simulate it at the backend and just call the previous popup when the second popup is closed. That keeps the frontend small and all the logic stays in ABAP in the backend what is my preferred approach. I adjusted the demo slightly.
