### ISSUE TITLE
demo 84

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#916]
hi @oblomov-dev 

demo 84 for message manager seems no to work,
probebly binidng related ?? i guess...

**Comment by oblomov-dev** [comment]
mhh but you never used the message manager for this demo right?

The xml view only contains input fields, which seem not to be correctly written into the model:
<img width="888" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/72733eba-71e1-432f-98d2-7f911b5efdd5">

<img width="1494" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/62a42ce2-f609-4e94-a3d1-7a7009109bb3">

<img width="1178" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/4bed83bd-c8e4-4da0-990e-7c23294de7b3">

But naming looks correct, so i am wondering at the moment...

**Comment by choper725** [comment]
i dont remember if i adjusted the 1.118 message manager in that demo,

but what doesnt work is the string constraits of the fields..

**Comment by oblomov-dev** [comment]
yes i checked it now with the other issue, but i dont get whats wrong here. to me everything looks correct so i am not sure if this is a bug due to the new JSON handling anymore.

when i copy the input of demo66 (where it works) to here:
https://github.com/abap2UI5/abap2UI5/pull/923

Then it doesn't work anymore, which means the reason is not the input field or the constraints command, but maybe other controls or circumstances which cause the problem?

**Comment by choper725** [comment]
maybe it got to do something with the event handling ??

in demo 66 this works, but.. every time the validation appear the screen seems to be re-rendered...

**Comment by oblomov-dev** [comment]
mhhh this one was not easy to find, i went back with tags till december, and this line was missing since then:
```
sap.ui.getCore().getMessageManager().registerObject(oView, true);
```
fixed now with:
https://github.com/abap2UI5/abap2UI5/pull/931

But it uses sap.ui.getCore, which i want to avoid for UI5 2.x compatibility. So we should still adjust this somehow from a certain point.

**Comment by choper725** [comment]
hi @oblomov-dev 
i tought about it and i think the funxtionality is correct, 
this should only work once message manager is activated, hence the above get message manager can be removed,
i just need to make a CC for messaging control as of version below 1.118,  with the same logic as the one you implemented (above 1.118)

could use your help on this one..

**Comment by oblomov-dev** [comment]
ok understand. then it also make sense that the other demo works. ok i will delete the above line again and we can solve it with cc message manager. yes if you need help, feel free to create an issue with your code if you run into problems.

**Comment by choper725** [comment]
removed message manager line from http_get in #940

**Comment by oblomov-dev** [comment]
Thank you! yes its good to have it also for lower releases, thank you for your work! i will close this issue, just open a new one when other problems with message manager occur or you need help.
