### ISSUE TITLE
debugging tools

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#944]
hi @oblomov-dev 

once getting an error in the view, is it possible to get the sent XML formatted correctly ?

i.e:
the view xml shows the error xml rather then the sent xml
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/7129f798-6d72-49ca-b8c8-ca8184fc86aa)

the view xml appear in the response like here unformatted
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/18c9b1cc-f724-44ed-9120-a15e2c26ea5c)

its not a bug, just an extra feature rather...

**Comment by oblomov-dev** [comment]
yes i think this is no problem, a check and replace at this position is needed:
https://github.com/abap2UI5/abap2UI5/blob/b747a388c75fbb5bc1b75b9d68fba32e74e42864/src/01/04/z2ui5_cl_fw_cc_debugging_tools.clas.abap#L73

Feel free to give it a try, otherwise i can also try to fix it next time i touch the debugging tools.

**Comment by choper725** [comment]
ill give it a try

**Comment by choper725** [comment]
im sure you would do that better, but it works :) 
#949
