### ISSUE TITLE
TableTree State

### ISSUE THREAD

**Issue by ssocratous71** [abap2UI5/abap2UI5#987]
Hi,
  when using a TableTree, is there a way to save current State (which nodes are expanded or not) in order to have the state restore after a server event? I have seen an attribute fo ODATA binding called treeState. Is there something similar to this?

Regards

S.Socratous

**Comment by choper725** [comment]
as far as i can see (and i am no expert at all) you should use event toggleOpenState to mark each row with a flag in the model if its expanded or collapsed and build some custom js function upon view rendering that expand rows from the model using expand method.

hope it helps,

**Comment by oblomov-dev** [comment]
Yes as far as I remember there was no simple way to save the collapsed/encollapsed information so try the approach of @choper725 or plan b could be that you use nested views and only rerender the view without the tree.

**Comment by choper725** [comment]
btw @oblomov-dev 
as i was working on a simple demo for this requested scenario, i was using demo 68 as a reference,
it seems that there is an issue with binding...

in recent PR (demo 178), i created a mirror expanded value tree based on the main tree.

and binded it to the main view model.

now once i update the values view togglestate event it seems that every time the table is getting deleted and only the recent change appears in the model.

check table PRODH_NODES_EX and event TOGGLE_STATE in demo 178.

**Comment by oblomov-dev** [comment]
Yes exactly that was the tree control issue! a simple property is_collapsed would solve everything but unfortunately does not exist.

Thank you for the PR, I will check the model update.

**Comment by oblomov-dev** [comment]
ok took a look and got the point. added demo 180 with tree models updates only and it works without problems. 

the problem here is that we open a popup and you want to exchange data of the main view. this is a new use case. before every server roundtrip we check if view/popup/nest/popover is active and then just send this model to the backend, see here:
https://github.com/abap2UI5/abap2UI5/blob/610194ed29b1a17eb477ed135f35be8c4adda0a4/src/01/02/z2ui5_cl_core_http_get.clas.abap#L320-L341

changed demo that the popup model is updated and the exchange of data is no problem. but now we have the root problem again that the tree encolapsed because of the model update of the popup. 

yes... different optionas now.

(1)
separating the tree and put it into a nested view that it is not touched by updating the model.
(2)
creating a frontend CC which implements the toggleOpenState method that no server roundtrip is needed.
(3)
Not sending the tree ext structure to the frontend and just keep it in the backend until the tree model can be updated
(4)
somehow extending the framework that data can be exchanged for the use case above, but that could create some more complexity

**Comment by choper725** [comment]
ill check the demo again, i didnt finish it, the part of rebuilding the tree with the collapsed nodes, i need to call a ja function on the tree object based on the mirror table with expanded bool.

ill check and let you know what i find.

i didnt understood fully what the root problem with the encapsulated tree.

**Comment by oblomov-dev** [comment]
the root problem (as far as i see/remember):
every time you update the model with the tree control, the tree gets fully unexpanded again.

yes just check it and let me know what you need. if way 4 is needed we could extend the event function with a new parameter that lets you decide which model you want to get with the event in the backend but i also don't want to make the framework more complex as needed.

**Comment by choper725** [comment]
the tree enexpanded is intended by ui5, its not a a2ui5 issue.

ill test the demo again, i just needed the data in the mirror table to persist once changed which you said you fixed

**Comment by choper725** [comment]
hi @oblomov-dev 
something still not working correctly, im checking what i did on demo 178

the scenario i excpect is once i expand the first node, i should get expanded in the first row,
after that event happen i expand the second row and and should get the first and the second row with expanded = X
the thing i get is a clean table (prodh_nodes_ex) every time the event triggers...

i dont remember it was like that,
the thing is that if the table is not binded to a model (straight abap only), the values are as expected... dont really know why binding the table erases the table every time a roundtrip happen.

**Comment by oblomov-dev** [comment]
Do you make a view_model update after the round trip or a popup_model_update?

The problem is when you press on a node the event of the popup is raised and the model of the popup is sent to the backend. Popup and views don't share the same model, they both use copies of the model from the backend. Depending on the model update method or event I am sure things get mixed up here...

Yes when you keep the values only in the backend and don't update them via frontend this unexpected behaviour can not occur.

Feel free to share your actual version of 178 again if you need help.

**Comment by choper725** [comment]
view model,
the popup rerender the control,
but why should it matter what i update ?? 

i get what you say about the seperation,
but i just ask myself, why should it matter where i call model update ? the view must be sent with it in order for json model to be refreshed ?

**Comment by oblomov-dev** [comment]
Yes the logic is as follows:

When you update the view, the depending model always gets updated.

But you also have the possibility to update the model of views only. For example to hold the scroll position, cursor etc.

Example 1:
Nested views with trees, we had this sample a while ago, by only updating the model of the nested view the tree in the main view keeps its state (ok maybe we solve this now with this issue) 

Example 2:
Popups in different apps. You can call apps which show Popups but the also hold the view in the background of the previous app which is a nice effect. Check the latest demos with layouts to see it.

But yes everything is just the best practice for the moment I am open minded for additional logic if it is needed.

**Comment by choper725** [comment]
yes its a nice feature to hold the bg view once a fragment is open.

but regarding the update model of view only,
it works on everything else besides a popup ?

meaning from main view i can update nested1 model ? because i got apps runing on older versions of a2ui5 which this logic is being used alot..
thats why i remember that updating each model upon event not from a dependent view was working..

**Comment by oblomov-dev** [comment]
yes you can update any model at any time. just the model which is sent to the backend is the one of the actual event means:
button click on popup sends the popup model
button click on nest1 sends nest1 model
etc.
but in the backend you can do at any time:
view_model
popup_model
nest_model

yes 097 was as far as i remember the sample when i changed the logic last time. and you can also check 066.

i think it is good to keep the logic as it is for the popup but if we find a way that also 066 and 097 works we can change the logic for nested views. Check the following code:
https://github.com/abap2UI5/abap2UI5/blob/89374e399cf98136e87b2aa8b53c6f6f8f71934a/src/01/02/z2ui5_cl_core_http_get.clas.abap#L377-L381
and here:
https://github.com/abap2UI5/abap2UI5/blob/89374e399cf98136e87b2aa8b53c6f6f8f71934a/src/01/02/z2ui5_cl_core_http_get.clas.abap#L358-L363
There the frontend models are updated after the backend processing.

I merge you PR, feel free to play around and let me know if you need something.

**Comment by choper725** [comment]
ohh ok so if i can do it in the backend anytime, so there is an issue if i bind a table to view=main, and during an event in the popup i cann view model update, the table binded to main is not updating.

thats what i tried to do with the mirror table

**Comment by oblomov-dev** [comment]
ah ok that might be but as far as is saw it, the table binded to main got updatet it just was not send to the backend again because the popup button event used the model of the (outdated) popup model. but yes maybe i mix something up here too, so just share the bug and we can check it.

**Comment by choper725** [comment]
ok ill update again the demo with the issue and post here the scenario.

**Comment by choper725** [comment]
updated demo 178
example:
table;
prodh_nodes_ex binded with view = main in main view render method.
expanded nodes (x2)
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/a66a0456-9644-4778-a488-84c5c258c9d0)

in model after model update, only the latest change is reflected (the second node that was expanded - the one with the horizontal arrow.
the vertical arrow is the first expansion that should be true also).

![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/131cba44-b6b4-4749-ad15-55667cc5af86)

**Comment by oblomov-dev** [comment]
yes popupmodel and viewmodel are not the same here, it works as follows:

you open a popup and only create a popup event, thats why the popup model is sent to the backend all the time. but the popup model never gets updated, because you do a view_model_update in the TOGGLE_STATE in the backend. Check the popup model after the second event:
<img width="1263" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/aaf121b2-2431-40a7-addc-2e91c0f541ad">
it has the initial state and this model is sent all the time to the backend (igonoring your changes of the main view). thats why only the latest changes are always reflected in the main view.

check this position, there you can see that a copy is made and popup and main view do not use the same view, they have parallel copies:
https://github.com/abap2UI5/abap2UI5/blob/89374e399cf98136e87b2aa8b53c6f6f8f71934a/src/01/02/z2ui5_cl_core_http_get.clas.abap#L358-L363

the question now is how to adjust abap2UI5? what do you need exactly?

**Comment by choper725** [comment]
is it possible to make model updates to update the model regardless of the view that bwing used. ?
like in this example, to update the main from popup,
or any other model updates from the backend regardless of the front

**Comment by oblomov-dev** [comment]
yes if you call a popup model update the data would get updated, but also the tree would unexpand because of the ui5 behaviour of rerendering etc.

It's a complex topic, there are a lot of side effects, but i am sure we will find a way step by step.

1) yes we can also just made a model update after a request but i think it will basically the same as if we create the whole model new, but we can try it out if needed, no problem.

2) i extended abap2UI5 and the demo, you can now import the viewname in the event method if you want to send specific model to the backend:
https://github.com/abap2UI5/abap2UI5-samples/blob/1bb5ce9669a718b78d86551a5c12fb6afdc0909b/src/z2ui5_cl_demo_app_178.clas.abap#L94
I think now you get the model updated as you expected before.

expect some bugs and let me know if it helps you.

**Comment by choper725** [comment]
ok ill try,

just on that note, does the view in the bind does something after all the changes.  ?

i tought that it specify which model to bind the variable to?

**Comment by oblomov-dev** [comment]
the view in the binding is important when you use nested views and you need to specify to which views the values belong to. check out the nested view demos to see the differences. i think the one where you select table entries needs this feature.

but to be honest, it might be that there are more elegant ways now, i am also learning. if we solve this problem here properly we can also try to solve the nested view logic in an easier or more straightforward way.

**Comment by choper725** [comment]
oh ok,
s_cnt can be, s_opt or s_set ?
cnt means continue?

**Comment by choper725** [comment]
seems the change does the trick,

meanwhile found a more "elegant" solution for this case.

updating demo 178.

regardless, i think the possibility of updating the main model is not breaking something, as far as i can see now.

**Comment by oblomov-dev** [comment]
great! nice to see that it works!
yes as long as this function is not needed, maybe i will build back the model update function, I want to keep it as simple as possible to reduce the maintenance effort.

**Comment by choper725** [comment]
well yeah, just figured a centrealized model handle might reduce maintanence no?

**Comment by oblomov-dev** [comment]
yes that would be the best but so far don't see a way with one model only which works for every use case

**Comment by ssocratous71** [comment]
Hi,
  thanks for all the helpful info so far. I have checked DEMO 178 and yes it works!. But what about if you have a tree tabli in the main view? Where will you setup the javascript setState and saveState. My situation is that I  have a table tree i nthe main view and each time there ia a view model update it reverts to its original state (closed). In this case where will the Javascript be placed?

Regards,

S.Socratous

**Comment by choper725** [comment]
hi @ssocratous71 
a demo of your code will help try to figure a solution.

**Comment by ssocratous71** [comment]
Here is a modified DEMO 178 where the tree table is in the main view and a rountrip is required whne you press he Add button. The tree loses its current state and returns to close position.
[z2ui5_cl_demo_app_178.txt](https://github.com/abap2UI5/abap2UI5/files/14614737/z2ui5_cl_demo_app_178.txt)

**Comment by choper725** [comment]
well in theroy it could work using timer checkactive flag.

been on it for couple of hours, not being able to make it work.
i guess without any CC or a independent js call (not via any event - like the old client->timer ) its not really doable.

but that opens up a talk about an idea, something like client->call_js( 'alert("call js from client")' ).
how about that @oblomov-dev  ?

**Comment by oblomov-dev** [comment]
@ssocratous71 feel free to add your source code as a sample and send PRs, then its easier to test and find a solution. added now @choper725 actual version as sample 116, and added it here:
<img width="946" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/3de9932a-2792-467b-91c1-83dabeab5edc">

@choper725 thank you for trying this out! maybe i deleted it accidentally or the property was still missing, but i added now toggleopenstate with: https://github.com/abap2UI5/abap2UI5/pull/1016

idea client->call_js( 'alert("call js from client")' ):
yes as always i am open minded for new features. After sending the JS to the frontend how do you want to execute it? I think you need this here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval?retiredLocale=de
but i am not sure if this is ok concerning security risks etc?
another option would be, to have a few functions predefined at the frontend like we do with onEventFrontend and you can choose only from one of these predefined options.

**Comment by choper725** [comment]
hi @oblomov-dev 
how about the way the old timer was setup, i dont think it used eval??

**Comment by oblomov-dev** [comment]
yes then its somehting like:
```
client->call_next( client->_event( ... ) ) 
```
for backend events and for frontend functions:
```
client->call_next( client->_event_frontend( ... ) ) 
```
but never had a use case for this so far...

**Comment by choper725** [comment]
is it implemented ?
i tuink i saw client->call_next before…
it might be handy, need to run some tests on it.

use case for it, i think i had one, 
getting a dms id from user via input and open a file from that dms, in short, call frontend event from backend event.

the call_next might solve this issue, as i was dont a hackish work around with the timer cc and check active

**Comment by oblomov-dev** [comment]
yes good idea, lets continue with the client event here https://github.com/abap2UI5/abap2UI5/issues/1018 and keep this issue only for the tree state. i try to take a look to it as soon as possible.

**Comment by choper725** [comment]
updated demo 116, @ssocratous71  check it

**Comment by ssocratous71** [comment]
The Demo works fine!!! Thanks! I will import the newest library and try it out.
